export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';

export const UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST' = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS' = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED: 'UPDATE_USER_FAILED' = 'UPDATE_USER_FAILED';

export const REGISTER_REQUEST: 'REGISTER_REQUEST' = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';

export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';

export const RESET_PASSWORD_STEP_ONE_REQUEST: 'RESET_PASSWORD_STEP_ONE_REQUEST' = 'RESET_PASSWORD_STEP_ONE_REQUEST';
export const RESET_PASSWORD_STEP_ONE_SUCCESS: 'RESET_PASSWORD_STEP_ONE_SUCCESS' = 'RESET_PASSWORD_STEP_ONE_SUCCESS';
export const RESET_PASSWORD_STEP_ONE_FAILED: 'RESET_PASSWORD_STEP_ONE_FAILED' = 'RESET_PASSWORD_STEP_ONE_FAILED';

export const RESET_PASSWORD_STEP_TWO_REQUEST: 'RESET_PASSWORD_STEP_TWO_REQUEST' = 'RESET_PASSWORD_STEP_TWO_REQUEST';
export const RESET_PASSWORD_STEP_TWO_SUCCESS: 'RESET_PASSWORD_STEP_TWO_SUCCESS' = 'RESET_PASSWORD_STEP_TWO_SUCCESS';
export const RESET_PASSWORD_STEP_TWO_FAILED: 'RESET_PASSWORD_STEP_TWO_FAILED' = 'RESET_PASSWORD_STEP_TWO_FAILED';

export const REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST' = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS' = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILED: 'REFRESH_TOKEN_FAILED' = 'REFRESH_TOKEN_FAILED';

export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';
