export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';

export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const UPDATE_INGREDIENT: 'UPDATE_INGREDIENT' = 'UPDATE_INGREDIENT';
export const REMOVE_INGREDIENT: 'REMOVE_INGREDIENT' = 'REMOVE_INGREDIENT';

export const CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST' = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS' = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILED: 'CREATE_ORDER_FAILED' = 'CREATE_ORDER_FAILED';

export const TOGGLE_ORDER_MODAL: 'TOGGLE_ORDER_MODAL' = 'TOGGLE_ORDER_MODAL';
