export const TOKEN_LIFETIME = 30;

export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';

export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED';

export const ADD_BUN = 'ADD_BUN';
export const ADD_INTER_INGREDIENT = 'ADD_INTER_INGREDIENT';
export const UPDATE_INTER_INGREDIENT = 'UPDATE_INTER_INGREDIENT';
export const REMOVE_INTER_INGREDIENT = 'REMOVE_INTER_INGREDIENT';

export const SET_CURRENT_INGREDIENT = 'SET_CURRENT_INGREDIENT';
export const RESET_CURRENT_INGREDIENT = 'RESET_CURRENT_INGREDIENT';

export const TOGGLE_INGREDIENT_MODAL = 'TOGGLE_INGREDIENT_MODAL';
export const TOGGLE_ORDER_MODAL = 'TOGGLE_ORDER_MODAL';
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';

export const RESET_PASSWORD_STEP_ONE = 'RESET_PASSWORD_STEP_ONE';
export const RESET_PASSWORD_STEP_ONE_SUCCESS = 'RESET_PASSWORD_STEP_ONE_SUCCESS';
export const RESET_PASSWORD_STEP_ONE_FAILED = 'RESET_PASSWORD_STEP_ONE_FAILED';

export const RESET_PASSWORD_STEP_TWO = 'RESET_PASSWORD_STEP_TWO';
export const RESET_PASSWORD_STEP_TWO_SUCCESS = 'RESET_PASSWORD_STEP_TWO_SUCCESS';
export const RESET_PASSWORD_STEP_TWO_FAILED = 'RESET_PASSWORD_STEP_TWO_FAILED';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const GET_NEW_TOKEN = 'GET_NEW_TOKEN';
export const GET_NEW_TOKEN_SUCCESS = 'GET_NEW_TOKEN_SUCCESS';
export const GET_NEW_TOKEN_FAILED = 'GET_NEW_TOKEN_FAILED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
