export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';

export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED';

export const ADD_BUN = 'ADD_BUN';
export const ADD_INTER_INGREDIENT = 'ADD_INTER_INGREDIENT';
export const UPDATE_INTER_INGREDIENT = 'UPDATE_INTER_INGREDIENT';
export const REMOVE_INTER_INGREDIENT = 'REMOVE_INTER_INGREDIENT';

export const SET_CURRENT_INGREDIENT = 'SET_CURRENT_INGREDIENT';
export const RESET_CURRENT_INGREDIENT = 'RESET_CURRENT_INGREDIENT';

export const TOGGLE_INGREDIENT_MODAL = 'TOGGLE_INGREDIENT_MODAL';
export const TOGGLE_ORDER_MODAL = 'TOGGLE_ORDER_MODAL';
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';
