// auth
export const REGISTER_REQUEST: 'REGISTER_REQUEST' = 'REGISTER_REQUEST';
export const REGISTER_REQUEST_SUCCESS: 'REGISTER_REQUEST_SUCCESS' = 'REGISTER_REQUEST_SUCCESS';
export const REGISTER_REQUEST_FAILED: 'REGISTER_REQUEST_FAILED' = 'REGISTER_REQUEST_FAILED';

export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS' = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILED: 'LOGIN_REQUEST_FAILED' = 'LOGIN_REQUEST_FAILED';

export const RESET_PASSWORD_STEP_ONE_REQUEST: 'RESET_PASSWORD_STEP_ONE_REQUEST' = 'RESET_PASSWORD_STEP_ONE_REQUEST';
export const RESET_PASSWORD_STEP_ONE_REQUEST_SUCCESS: 'RESET_PASSWORD_STEP_ONE_REQUEST_SUCCESS' = 'RESET_PASSWORD_STEP_ONE_REQUEST_SUCCESS';
export const RESET_PASSWORD_STEP_ONE_REQUEST_FAILED: 'RESET_PASSWORD_STEP_ONE_REQUEST_FAILED' = 'RESET_PASSWORD_STEP_ONE_REQUEST_FAILED';

export const RESET_PASSWORD_STEP_TWO_REQUEST: 'RESET_PASSWORD_STEP_TWO_REQUEST' = 'RESET_PASSWORD_STEP_TWO_REQUEST';
export const RESET_PASSWORD_STEP_TWO_REQUEST_SUCCESS: 'RESET_PASSWORD_STEP_TWO_REQUEST_SUCCESS' = 'RESET_PASSWORD_STEP_TWO_REQUEST_SUCCESS';
export const RESET_PASSWORD_STEP_TWO_REQUEST_FAILED: 'RESET_PASSWORD_STEP_TWO_REQUEST_FAILED' = 'RESET_PASSWORD_STEP_TWO_REQUEST_FAILED';

export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_REQUEST_SUCCESS: 'LOGOUT_REQUEST_SUCCESS' = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILED: 'LOGOUT_REQUEST_FAILED' = 'LOGOUT_REQUEST_FAILED';

export const GET_NEW_TOKEN_REQUEST: 'GET_NEW_TOKEN_REQUEST' = 'GET_NEW_TOKEN_REQUEST';
export const GET_NEW_TOKEN_REQUEST_SUCCESS: 'GET_NEW_TOKEN_REQUEST_SUCCESS' = 'GET_NEW_TOKEN_REQUEST_SUCCESS';
export const GET_NEW_TOKEN_REQUEST_FAILED: 'GET_NEW_TOKEN_REQUEST_FAILED' = 'GET_NEW_TOKEN_REQUEST_FAILED';

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_REQUEST_SUCCESS: 'GET_USER_REQUEST_SUCCESS' = 'GET_USER_REQUEST_SUCCESS';
export const GET_USER_REQUEST_FAILED: 'GET_USER_REQUEST_FAILED' = 'GET_USER_REQUEST_FAILED';

export const UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST' = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_REQUEST_SUCCESS: 'UPDATE_USER_REQUEST_SUCCESS' = 'UPDATE_USER_REQUEST_SUCCESS';
export const UPDATE_USER_REQUEST_FAILED: 'UPDATE_USER_REQUEST_FAILED' = 'UPDATE_USER_REQUEST_FAILED';

// burger
export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_REQUEST_SUCCESS: 'GET_INGREDIENTS_REQUEST_SUCCESS' = 'GET_INGREDIENTS_REQUEST_SUCCESS';
export const GET_INGREDIENTS_REQUEST_FAILED: 'GET_INGREDIENTS_REQUEST_FAILED' = 'GET_INGREDIENTS_REQUEST_FAILED';

export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';

export const ADD_INTER_INGREDIENT: 'ADD_INTER_INGREDIENT' = 'ADD_INTER_INGREDIENT';
export const UPDATE_INTER_INGREDIENT: 'UPDATE_INTER_INGREDIENT' = 'UPDATE_INTER_INGREDIENT';
export const REMOVE_INTER_INGREDIENT: 'REMOVE_INTER_INGREDIENT' = 'REMOVE_INTER_INGREDIENT';

export const SET_CURRENT_INGREDIENT: 'SET_CURRENT_INGREDIENT' = 'SET_CURRENT_INGREDIENT';
export const RESET_CURRENT_INGREDIENT: 'RESET_CURRENT_INGREDIENT' = 'RESET_CURRENT_INGREDIENT';

// order
export const CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST' = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_REQUEST_SUCCESS: 'CREATE_ORDER_REQUEST_SUCCESS' = 'CREATE_ORDER_REQUEST_SUCCESS';
export const CREATE_ORDER_REQUEST_FAILED: 'CREATE_ORDER_REQUEST_FAILED' = 'CREATE_ORDER_REQUEST_FAILED';

// UI
export const TOGGLE_INGREDIENT_MODAL: 'TOGGLE_INGREDIENT_MODAL' = 'TOGGLE_INGREDIENT_MODAL';

export const TOGGLE_ORDER_MODAL: 'TOGGLE_ORDER_MODAL' = 'TOGGLE_ORDER_MODAL';

export const SET_CURRENT_TAB: 'SET_CURRENT_TAB' = 'SET_CURRENT_TAB';

// WebSocket
export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_AUTH_CONNECTION_START: 'WS_AUTH_CONNECTION_START' = 'WS_AUTH_CONNECTION_START';
export const WS_CONNECTION_CLOSE: 'WS_CONNECTION_CLOSE' = 'WS_CONNECTION_CLOSE';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
